// Auto-generated by: npm run supabase:types
// Manual edits will be overwritten on next generation.
// Re-run after schema changes: npm run supabase:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string
          avatar_url: string | null
          bio: string | null
          dietary_preferences: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name: string
          avatar_url?: string | null
          bio?: string | null
          dietary_preferences?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string
          avatar_url?: string | null
          bio?: string | null
          dietary_preferences?: string[]
          updated_at?: string
        }
        Relationships: []
      }
      recipes_cloud: {
        Row: {
          id: string
          author_id: string
          data: Json
          visibility: 'private' | 'friends' | 'public'
          published_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          author_id: string
          data: Json
          visibility?: 'private' | 'friends' | 'public'
          published_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          author_id?: string
          data?: Json
          visibility?: 'private' | 'friends' | 'public'
          published_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'recipes_cloud_author_id_fkey'
            columns: ['author_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      friendships: {
        Row: {
          id: string
          requester_id: string
          addressee_id: string
          status: 'pending' | 'accepted' | 'blocked'
          created_at: string
          responded_at: string | null
        }
        Insert: {
          id?: string
          requester_id: string
          addressee_id: string
          status?: 'pending' | 'accepted' | 'blocked'
          created_at?: string
          responded_at?: string | null
        }
        Update: {
          status?: 'pending' | 'accepted' | 'blocked'
          responded_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'friendships_requester_id_fkey'
            columns: ['requester_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'friendships_addressee_id_fkey'
            columns: ['addressee_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      reactions: {
        Row: {
          id: string
          user_id: string
          recipe_id: string
          type: 'like' | 'bookmark' | 'emoji'
          emoji_code: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          recipe_id: string
          type: 'like' | 'bookmark' | 'emoji'
          emoji_code?: string | null
          created_at?: string
        }
        Update: {
          type?: 'like' | 'bookmark' | 'emoji'
          emoji_code?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'reactions_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'reactions_recipe_id_fkey'
            columns: ['recipe_id']
            isOneToOne: false
            referencedRelation: 'recipes_cloud'
            referencedColumns: ['id']
          }
        ]
      }
      comments: {
        Row: {
          id: string
          user_id: string
          recipe_id: string
          parent_comment_id: string | null
          body: string
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          recipe_id: string
          parent_comment_id?: string | null
          body: string
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          body?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'comments_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'comments_recipe_id_fkey'
            columns: ['recipe_id']
            isOneToOne: false
            referencedRelation: 'recipes_cloud'
            referencedColumns: ['id']
          }
        ]
      }
      ratings: {
        Row: {
          id: string
          user_id: string
          recipe_id: string
          score: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          recipe_id: string
          score: number
          created_at?: string
        }
        Update: {
          score?: number
        }
        Relationships: [
          {
            foreignKeyName: 'ratings_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'ratings_recipe_id_fkey'
            columns: ['recipe_id']
            isOneToOne: false
            referencedRelation: 'recipes_cloud'
            referencedColumns: ['id']
          }
        ]
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          payload: Json
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          payload?: Json
          read_at?: string | null
          created_at?: string
        }
        Update: {
          read_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'notifications_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      meal_plans_cloud: {
        Row: {
          id: string
          owner_id: string
          data: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          owner_id: string
          data: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          data?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'meal_plans_cloud_owner_id_fkey'
            columns: ['owner_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      shopping_lists_cloud: {
        Row: {
          id: string
          owner_id: string
          data: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          owner_id: string
          data: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          data?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'shopping_lists_cloud_owner_id_fkey'
            columns: ['owner_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      recipe_visibility: 'private' | 'friends' | 'public'
      friendship_status: 'pending' | 'accepted' | 'blocked'
      reaction_type: 'like' | 'bookmark' | 'emoji'
    }
    CompositeTypes: Record<string, never>
  }
}

// ─── Convenience aliases ──────────────────────────────────────────────────────

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type Inserts<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type Updates<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']

export type Profile = Tables<'profiles'>
export type CloudRecipe = Tables<'recipes_cloud'>
export type CloudMealPlan = Tables<'meal_plans_cloud'>
export type CloudShoppingList = Tables<'shopping_lists_cloud'>
export type Friendship = Tables<'friendships'>
export type Reaction = Tables<'reactions'>
export type Comment = Tables<'comments'>
export type Rating = Tables<'ratings'>
export type Notification = Tables<'notifications'>

export type RecipeVisibility = Database['public']['Enums']['recipe_visibility']
export type FriendshipStatus = Database['public']['Enums']['friendship_status']
export type ReactionType = Database['public']['Enums']['reaction_type']
