// Auto-generated by: npm run supabase:types
// Manual edits will be overwritten on next generation.
// Re-run after schema changes: npm run supabase:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string
          avatar_url: string | null
          bio: string | null
          dietary_preferences: string[]
          notification_muted_types: string[]
          role: 'user' | 'admin'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name: string
          avatar_url?: string | null
          bio?: string | null
          dietary_preferences?: string[]
          notification_muted_types?: string[]
          role?: 'user' | 'admin'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string
          avatar_url?: string | null
          bio?: string | null
          dietary_preferences?: string[]
          notification_muted_types?: string[]
          role?: 'user' | 'admin'
          updated_at?: string
        }
        Relationships: []
      }
      recipes_cloud: {
        Row: {
          id: string
          author_id: string
          data: Json
          visibility: 'private' | 'friends' | 'public'
          published_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          author_id: string
          data: Json
          visibility?: 'private' | 'friends' | 'public'
          published_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          author_id?: string
          data?: Json
          visibility?: 'private' | 'friends' | 'public'
          published_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'recipes_cloud_author_id_fkey'
            columns: ['author_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      friendships: {
        Row: {
          id: string
          requester_id: string
          addressee_id: string
          status: 'pending' | 'accepted' | 'blocked'
          created_at: string
          responded_at: string | null
        }
        Insert: {
          id?: string
          requester_id: string
          addressee_id: string
          status?: 'pending' | 'accepted' | 'blocked'
          created_at?: string
          responded_at?: string | null
        }
        Update: {
          status?: 'pending' | 'accepted' | 'blocked'
          responded_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'friendships_requester_id_fkey'
            columns: ['requester_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'friendships_addressee_id_fkey'
            columns: ['addressee_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      reactions: {
        Row: {
          id: string
          user_id: string
          recipe_id: string
          type: 'like' | 'bookmark' | 'emoji'
          emoji_code: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          recipe_id: string
          type: 'like' | 'bookmark' | 'emoji'
          emoji_code?: string | null
          created_at?: string
        }
        Update: {
          type?: 'like' | 'bookmark' | 'emoji'
          emoji_code?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'reactions_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'reactions_recipe_id_fkey'
            columns: ['recipe_id']
            isOneToOne: false
            referencedRelation: 'recipes_cloud'
            referencedColumns: ['id']
          },
        ]
      }
      comments: {
        Row: {
          id: string
          user_id: string
          recipe_id: string
          parent_comment_id: string | null
          body: string
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          recipe_id: string
          parent_comment_id?: string | null
          body: string
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          body?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'comments_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'comments_recipe_id_fkey'
            columns: ['recipe_id']
            isOneToOne: false
            referencedRelation: 'recipes_cloud'
            referencedColumns: ['id']
          },
        ]
      }
      ratings: {
        Row: {
          id: string
          user_id: string
          recipe_id: string
          score: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          recipe_id: string
          score: number
          created_at?: string
        }
        Update: {
          score?: number
        }
        Relationships: [
          {
            foreignKeyName: 'ratings_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'ratings_recipe_id_fkey'
            columns: ['recipe_id']
            isOneToOne: false
            referencedRelation: 'recipes_cloud'
            referencedColumns: ['id']
          },
        ]
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          payload: Json
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          payload?: Json
          read_at?: string | null
          created_at?: string
        }
        Update: {
          read_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'notifications_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      households: {
        Row: {
          id: string
          name: string
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'households_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      household_members: {
        Row: {
          household_id: string
          user_id: string
          role: 'owner' | 'member'
          joined_at: string
        }
        Insert: {
          household_id: string
          user_id: string
          role?: 'owner' | 'member'
          joined_at?: string
        }
        Update: {
          role?: 'owner' | 'member'
        }
        Relationships: [
          {
            foreignKeyName: 'household_members_household_id_fkey'
            columns: ['household_id']
            isOneToOne: false
            referencedRelation: 'households'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'household_members_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      household_invitations: {
        Row: {
          id: string
          household_id: string
          invited_by: string
          invitee_email: string
          token: string
          status: 'pending' | 'accepted' | 'declined' | 'expired'
          created_at: string
          expires_at: string
        }
        Insert: {
          id?: string
          household_id: string
          invited_by: string
          invitee_email: string
          token?: string
          status?: 'pending' | 'accepted' | 'declined' | 'expired'
          created_at?: string
          expires_at?: string
        }
        Update: {
          status?: 'pending' | 'accepted' | 'declined' | 'expired'
        }
        Relationships: [
          {
            foreignKeyName: 'household_invitations_household_id_fkey'
            columns: ['household_id']
            isOneToOne: false
            referencedRelation: 'households'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'household_invitations_invited_by_fkey'
            columns: ['invited_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      meal_plans_cloud: {
        Row: {
          id: string
          owner_id: string
          data: Json
          household_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          owner_id: string
          data: Json
          household_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          data?: Json
          household_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'meal_plans_cloud_owner_id_fkey'
            columns: ['owner_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'meal_plans_cloud_household_id_fkey'
            columns: ['household_id']
            isOneToOne: false
            referencedRelation: 'households'
            referencedColumns: ['id']
          },
        ]
      }
      shopping_lists_cloud: {
        Row: {
          id: string
          owner_id: string
          data: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          owner_id: string
          data: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          data?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'shopping_lists_cloud_owner_id_fkey'
            columns: ['owner_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      friend_invites: {
        Row: {
          id: string
          user_id: string
          token: string
          expires_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          token?: string
          expires_at?: string
          created_at?: string
        }
        Update: {
          expires_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'friend_invites_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      groups: {
        Row: {
          id: string
          name: string
          description: string | null
          avatar_url: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          avatar_url?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          description?: string | null
          avatar_url?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'groups_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      group_members: {
        Row: {
          group_id: string
          user_id: string
          role: 'admin' | 'member'
          joined_at: string
        }
        Insert: {
          group_id: string
          user_id: string
          role?: 'admin' | 'member'
          joined_at?: string
        }
        Update: {
          role?: 'admin' | 'member'
        }
        Relationships: [
          {
            foreignKeyName: 'group_members_group_id_fkey'
            columns: ['group_id']
            isOneToOne: false
            referencedRelation: 'groups'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'group_members_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      group_recipes: {
        Row: {
          id: string
          group_id: string
          recipe_id: string
          added_by: string
          added_at: string
        }
        Insert: {
          id?: string
          group_id: string
          recipe_id: string
          added_by: string
          added_at?: string
        }
        Update: Record<string, never>
        Relationships: [
          {
            foreignKeyName: 'group_recipes_group_id_fkey'
            columns: ['group_id']
            isOneToOne: false
            referencedRelation: 'groups'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'group_recipes_recipe_id_fkey'
            columns: ['recipe_id']
            isOneToOne: false
            referencedRelation: 'recipes_cloud'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'group_recipes_added_by_fkey'
            columns: ['added_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      app_settings: {
        Row: {
          key: string
          value: Json
          sensitive: boolean
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          key: string
          value?: Json
          sensitive?: boolean
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          key?: string
          value?: Json
          sensitive?: boolean
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'app_settings_updated_by_fkey'
            columns: ['updated_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      is_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
    }
    Enums: {
      recipe_visibility: 'private' | 'friends' | 'public'
      friendship_status: 'pending' | 'accepted' | 'blocked'
      reaction_type: 'like' | 'bookmark' | 'emoji'
      household_member_role: 'owner' | 'member'
      household_invitation_status: 'pending' | 'accepted' | 'declined' | 'expired'
      user_role: 'user' | 'admin'
    }
    CompositeTypes: Record<string, never>
  }
}

// ─── Convenience aliases ──────────────────────────────────────────────────────

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type Inserts<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type Updates<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']

export type Profile = Tables<'profiles'>
export type CloudRecipe = Tables<'recipes_cloud'>
export type CloudMealPlan = Tables<'meal_plans_cloud'>
export type CloudShoppingList = Tables<'shopping_lists_cloud'>
export type Friendship = Tables<'friendships'>
export type Reaction = Tables<'reactions'>
export type Comment = Tables<'comments'>
export type Rating = Tables<'ratings'>
export type Notification = Tables<'notifications'>

export type RecipeVisibility = Database['public']['Enums']['recipe_visibility']
export type FriendshipStatus = Database['public']['Enums']['friendship_status']
export type ReactionType = Database['public']['Enums']['reaction_type']
export type HouseholdMemberRole = Database['public']['Enums']['household_member_role']
export type HouseholdInvitationStatus = Database['public']['Enums']['household_invitation_status']
export type UserRole = Database['public']['Enums']['user_role']

export type Household = Tables<'households'>
export type HouseholdMember = Tables<'household_members'>
export type HouseholdInvitation = Tables<'household_invitations'>
export type FriendInvite = Tables<'friend_invites'>
export type Group = Tables<'groups'>
export type GroupMember = Tables<'group_members'>
export type GroupRecipe = Tables<'group_recipes'>
export type AppSetting = Tables<'app_settings'>

// ─── Storage ──────────────────────────────────────────────────────────────────

/** Bucket IDs used in Supabase Storage. */
export type StorageBucket = 'recipe-images'

/** Public URL shape returned by supabase.storage.from(bucket).getPublicUrl(). */
export interface StoragePublicUrl {
  publicUrl: string
}
