/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { registerRoute } from 'workbox-routing'
import { BackgroundSyncPlugin } from 'workbox-background-sync'

declare const self: ServiceWorkerGlobalScope

// Background Sync API — not yet in TypeScript stdlib (experimental)
interface SyncEvent extends ExtendableEvent {
  readonly tag: string
  readonly lastChance: boolean
}

// Clean up caches from previous SW versions
cleanupOutdatedCaches()

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST)

// ─── Runtime caching ───────────────────────────────────────────────────────

// Supabase REST API — network-first with background sync for mutations
const bgSyncPlugin = new BackgroundSyncPlugin('mise-sync-queue', {
  maxRetentionTime: 24 * 60, // keep queued requests up to 24 hours
})

registerRoute(
  ({ url }) => /^https:\/\/[a-z0-9]+\.supabase\.co\/rest\//i.test(url.href),
  new NetworkFirst({
    cacheName: 'supabase-api',
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 24 * 60 * 60 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      bgSyncPlugin,
    ],
  }),
  'GET'
)

// Supabase Storage (images) — stale-while-revalidate
registerRoute(
  ({ url }) => /^https:\/\/[a-z0-9]+\.supabase\.co\/storage\//i.test(url.href),
  new StaleWhileRevalidate({
    cacheName: 'supabase-storage',
    plugins: [
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 7 * 24 * 60 * 60 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
)

// External images (recipe thumbnails, etc.)
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
)

// Google Fonts
registerRoute(
  ({ url }) => /^https:\/\/fonts\.(googleapis|gstatic)\.com\//i.test(url.href),
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 365 * 24 * 60 * 60 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
)

// ─── Background Sync event ─────────────────────────────────────────────────
// Workbox's BackgroundSyncPlugin automatically handles replay of queued requests.
// Additionally notify all clients so they can pull fresh data after reconnect.

self.addEventListener('sync', (event: SyncEvent) => {
  if (event.tag === 'mise-pull') {
    event.waitUntil(
      self.clients.matchAll({ includeUncontrolled: true, type: 'window' }).then((clients) => {
        clients.forEach((client) => client.postMessage({ type: 'BACKGROUND_SYNC' }))
      })
    )
  }
})

// ─── Push notifications ────────────────────────────────────────────────────
// Placeholder — push subscription management is handled by the app.
// When push messages arrive, display a notification.

self.addEventListener('push', (event: PushEvent) => {
  if (!event.data) return
  let data: { title?: string; body?: string; url?: string }
  try {
    data = event.data.json() as { title?: string; body?: string; url?: string }
  } catch {
    return
  }

  const title = data.title ?? 'Mise'
  const body = data.body ?? 'You have a new notification.'
  const url = data.url ?? '/'

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      data: { url },
    })
  )
})

self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close()
  const url: string = (event.notification.data as { url?: string })?.url ?? '/'
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      const existing = clients.find((c) => c.url === url && 'focus' in c)
      if (existing) return (existing as WindowClient).focus()
      return self.clients.openWindow(url)
    })
  )
})
